//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class criteria
    {
        public criteria()
        {
            this.pages = new HashSet<page>();
            this.keywords = new HashSet<keyword>();
        }
    
        public int id { get; set; }
        public string criterianame { get; set; }
    
        public virtual ICollection<page> pages { get; set; }
        public virtual ICollection<keyword> keywords { get; set; }
    }
}
