//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBNew
    {
        public int id { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string pagename { get; set; }
        public string keyword { get; set; }
        public string post_id { get; set; }
    }
}
