//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class keyword
    {
        public int id { get; set; }
        public string keywords { get; set; }
        public int cirteriaId { get; set; }
    
        public virtual criteria criteria { get; set; }
    }
}
