//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public int id { get; set; }
        public string pagename { get; set; }
        public string pagefbid { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> lastcheckdate { get; set; }
        public int criteriaId { get; set; }
    
        public virtual criteria criteria { get; set; }
    }
}
